version: '2'
services:
    nginx:
        image: phpdockerio/nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ../:/var/www
            # - ../:/var/www:ro # at production
            - ./nginx/logs:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

        links:
            - php-fpm
        depends_on:
            - db

    php-fpm:
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ../:/var/www
            - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        links:
            - db
        depends_on:
            - db

    db:
        image: mysql:5.7
        env_file: ../.env.docker
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql

    adminer:
        image: adminer:latest
        ports:
            - "8081:8080"
        links:
            - db
        depends_on:
            - db
